# Generated by Django 3.2.4 on 2021-06-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='advertisementtype',
            options={'verbose_name': 'Тип объявления', 'verbose_name_plural': 'Типы объявлений'},
        ),
    ]
