# Generated by Django 3.2.4 on 2021-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20210611_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='кол-во просмотров'),
        ),
    ]
