# Generated by Django 3.2.4 on 2021-06-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisement_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='author',
            name='nickname',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ник'),
        ),
        migrations.AddField(
            model_name='author',
            name='telegram',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='author',
            name='viber',
            field=models.CharField(blank=True, max_length=20, verbose_name='Viber'),
        ),
        migrations.AddField(
            model_name='author',
            name='web',
            field=models.URLField(blank=True, verbose_name='веб-страница'),
        ),
        migrations.AddField(
            model_name='author',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
