# Generated by Django 3.2.4 on 2021-06-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_auto_20210612_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='published_end',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='views_count',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(default=None, upload_to='files/'),
        ),
    ]
